name "labus"
maintainer "Serge A. Salamanka"
maintainer_email "skif@grid.by"
license "Apache 2.0"
description "Install and configure Labus from Omnibus"
long_description "Install and configure Labus from Omnibus"
version "0.0.1"
recipe "labus", "Configures Labus from Omnibus"

depends "gitlab"
